### PR TITLE
Add cog sample

### PR DESCRIPTION
**Pull request by ketourneau**
We would like to add the possibility of reading COG file in itowns and we need some sample data for example.
We convert geotiff to cog with gdal (https://www.cogeo.org/)

### CODE REVIEW

**Comment by Pourfex** [comment]
This sample was made with gdal 3.8.1 with this command : 

gdal_translate input.tif output.tif -of COG -co COMPRESS=LZW.

**Comment by jailln** [comment]
Thanks for providing this sample :) 

Could you please add a readme next to the file indicating:
* What is the source data
* The gdal command you provided used to create it
* licenses if any needed

**Comment by ketourneau** [comment]
I added README and LICENSE file.

**Comment by jailln** [comment]
Thanks :)

**Pull request merged**
